package com.klk.hams.data.db

import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.SupportSQLiteOpenHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Verifies MIGRATION_4_5 directly, without MigrationTestHelper (this project does
 * not export Room schemas, so the helper can't materialise a v4 database). We build
 * the v4 `diagnostics` table by hand, run the migration, and assert the new columns.
 */
@RunWith(AndroidJUnit4::class)
class DiagnosticMigrationTest {

    private val dbName = "migration-test-diag"

    @Test
    fun migrate4to5_addsColumns_andPreservesRows() {
        val ctx = ApplicationProvider.getApplicationContext<android.content.Context>()
        ctx.deleteDatabase(dbName)

        val config = SupportSQLiteOpenHelper.Configuration.builder(ctx)
            .name(dbName)
            .callback(object : SupportSQLiteOpenHelper.Callback(4) {
                override fun onCreate(db: SupportSQLiteDatabase) {
                    // v4 diagnostics table, as generated by Room before this change.
                    db.execSQL(
                        "CREATE TABLE IF NOT EXISTS diagnostics (" +
                            "id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, " +
                            "type TEXT NOT NULL, timestamp TEXT NOT NULL, " +
                            "battery_pct REAL, created_at TEXT NOT NULL)"
                    )
                }
                override fun onUpgrade(db: SupportSQLiteDatabase, oldV: Int, newV: Int) {}
            })
            .build()

        val helper = FrameworkSQLiteOpenHelperFactory().create(config)
        try {
            helper.writableDatabase.use { db ->
                db.execSQL(
                    "INSERT INTO diagnostics (type, timestamp, battery_pct, created_at) " +
                        "VALUES ('boot','2026-07-02T00:00:00Z',88.0,'2026-07-02T00:00:00Z')"
                )

                MIGRATION_4_5.migrate(db)

                db.query("SELECT pushed, lat_decimal, speed_kmh FROM diagnostics").use { c ->
                    assertEquals(1, c.count)
                    c.moveToFirst()
                    assertEquals(0, c.getInt(0))   // pushed default
                    assertTrue(c.isNull(1))         // lat null for the legacy row
                    assertTrue(c.isNull(2))         // speed null
                }
            }
        } finally {
            helper.close()
            ctx.deleteDatabase(dbName)
        }
    }
}
